import 'bootstrap/dist/css/bootstrap.css';
import './style.css'
import './globals.css'
import Header from './components/header/Header';
import Footer from './components/footer/Footer';
import { Toaster } from "react-hot-toast";
import Providers from './context/Provider';
import "react-datepicker/dist/react-datepicker.css";
import PaddingFixed from './PaddingFixed';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import 'react-loading-skeleton/dist/skeleton.css'


export const metadata = {
  title: 'Tripherder',
  // description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <PaddingFixed>
            {children}
          </PaddingFixed>
          <Toaster />
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
